namespace: gitops-dev

frontend:
  replicas: 1
  image:
    tag: "1.0.0"

backend:
  replicas: 1
  image:
    tag: "1.1.0"
  environment: DEV

redis:
  replicas: 1

ingress:
  enabled: true
  host: gitops-dev.local