apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: gitops-project

  source:
    repoURL: https://github.com/hs2002-18/gitops-microservices-config.git
    targetRevision: main
    path: observability
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true