apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: gitops-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: gitops-frontend
  template:
    metadata:
      labels:
        app: gitops-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}