apiVersion: v1
kind: Service
metadata:
  name: gitops-redis
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: gitops-redis
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP