apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: gitops-redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: gitops-redis
  template:
    metadata:
      labels:
        app: gitops-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.service.port }}